version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/dist
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 60
    - location: scripts/install.sh
      timeout: 240
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
  ValidateService:
    - location: scripts/validate.sh
      timeout: 30
